# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

KEYSTORE_PATH = ENV["KEYSTORE_PATH"]
KEYSTORE_KEY_ALIAS = ENV["KEYSTORE_KEY_ALIAS"]
KEYSTORE_KEY_PASSWORD = ENV["KEYSTORE_KEY_PASSWORD"]
KEYSTORE_STORE_PASSWORD = ENV["KEYSTORE_STORE_PASSWORD"]
APK_OUTPUT_PATH = "./release"
CACHE_PATH = "./.cache"


platform :android do

  desc "Deploy alpha version"
  lane :alpha do
    sh "pnpm install -g @ionic/cli"
    sh "pnpm install"
    sh "ionic cap sync android"
    sh "ionic cap build android --no-open"
    gradle(
          task: "clean bundleRelease",
          project_dir: 'android/',
          print_command: false,
          properties: {
            "android.injected.signing.store.file" => "#{KEYSTORE_PATH}",
            "android.injected.signing.store.password" => "#{KEYSTORE_STORE_PASSWORD}",
            "android.injected.signing.key.alias" => "#{KEYSTORE_KEY_ALIAS}",
            "android.injected.signing.key.password" => "#{KEYSTORE_KEY_PASSWORD}",
          })
    aab_path = "android/app/build/outputs/bundle/release/app-release.aab"
    bundletool(
      ks_path: KEYSTORE_PATH,
      ks_password: KEYSTORE_STORE_PASSWORD,
      ks_key_alias: KEYSTORE_KEY_ALIAS,
      ks_key_alias_password: KEYSTORE_KEY_PASSWORD,
      bundletool_version: '1.10.0',
      aab_path: aab_path,
      apk_output_path: APK_OUTPUT_PATH,
      verbose: true,
      cache_path: CACHE_PATH
    )
  end
end
