name: 🤖🎯 Publish Android Beta Version

on:
  pull_request:
    branches: ['main']

jobs:
  distribute:
    uses: ForkbombEu/ship-capacitor-apps/.github/workflows/ship_android.yml@v1
    with:
      backend-url: ${{ vars.PUBLIC_BACKEND_URL }}
      lane: beta
    secrets:
      keystore-file: ${{ secrets.PLAYSTORE_KEYSTORE }}
      service-account: ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT }}
      keystore-alias: ${{ secrets.PLAYSTORE_KEYSTORE_ALIAS }}
      keystore-password: ${{ secrets.PLAYSTORE_KEYSTORE_PASSWORD }}
      keystore-key-password: ${{ secrets.PLAYSTORE_KEYSTORE_KEY_PASSWORD }}

