name: 🔥📲 Publish on Firebase Distribution

on:
  pull_request:
    branches: ['main']

jobs:
  distribute:
    uses: ForkbombEu/ship-capacitor-apps/.github/workflows/ship_android.yml@main
    with:
      backend-url: ${{ github.env.test.vars.PUBLIC_BACKEND_URL }}
      lane: distribute
    secrets:
      keystore-file: ${{ secrets.ANDROID_KEYSTORE_FILE }}
      service-account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      keystore-alias: ${{ secrets.KEYSTORE_KEY_ALIAS }}
      keystore-password: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
      keystore-key-password: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
      firebase-app-id: ${{ secrets.FIREBASE_APP_ID }}