name: 🤖🌈 Submit for review on App Store

on:
  push:
    branches: ['main']

jobs:
  distribute_ios:
    uses: ForkbombEu/ship-capacitor-apps/.github/workflows/ship_ios.yml@main
    with:
      backend-url: ${{ vars.PUBLIC_BACKEND_URL }}
      lane: ios production
      DEMO_USER: ${{ github.env.ios.vars.USER_EMAIL }}
      DEMO_PASSWORD: ${{ github.env.ios.vars.USER_PASSWORD }}
    secrets:
      APP_STORE_CONNECT_TEAM_ID: ${{ secrets.APP_STORE_CONNECT_TEAM_ID }}
      BUNDLE_IDENTIFIER: com.didroom.verifier
      BUILD_CERTIFICATE_BASE64: ${{ secrets.IOS_BUILD_CERTIFICATE }}
      BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.IOS_BUILD_PROVISION_PROFILE }}
      APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
      APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
      APPLE_KEY_CONTENT: ${{ secrets.APPLE_KEY_CONTENT }}
      APPLE_PROFILE_NAME: ${{ secrets.APPLE_PROFILE_NAME }}
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}